# Generated by Django 3.2.13 on 2022-05-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalgallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='articles/travel.jpg', null=True, upload_to='articles/'),
        ),
    ]
